### ISSUE TITLE
Arduino library

### ISSUE THREAD

**Issue by RCGV1** [LieBtrau/rattlegram-openmodem#1]
Are you planning on making this into an Arduino library? I am interested in using something like rattlegram for an Arduino project.

**Comment by LieBtrau** [comment]
Hi Benjamin,

It's possible to turn this into a library, but I'm a bit hesitant to do that:

1. The user would still need to provide audio samples to the library (either through ADC or audio codec).
2. The library is too computationally intensive to be run on most Arduino platforms.  Up to now, I've only run it on an ESP32 (240MHz) and even the ESP32 isn't capable of running this library in real time.  The Teensy 4.0 looks promising, but I haven't tried it yet.  
3. I'm not pointing at you (you seem to be an experienced programmer), but I don't want to support people who tried to run it on an Arduino Uno and complain that it doesn't compile/build/work.

What are you planning to use it for?  I might turn it into a library (Arduino, PlatformIO whatever), but I need a more performant processor than the ESP32 to test it.  Any other suggestions besides the Teensy 4.0 are welcome.

Regards,

Christoph
